In [1]:
import numpy as np

In [4]:
np.random.randint(1,100)

55

In [5]:
np.random.randint(1, 100, 10)

array([ 5, 95, 88, 68, 28, 85, 59, 83, 17, 56])

In [6]:
np.random.randint(1, 100, size = 10)

array([17, 20, 87, 92,  6, 58, 49, 16, 55, 77])

In [7]:
np.random.randint(5, size = 10)

array([2, 2, 2, 4, 4, 2, 2, 1, 0, 1])

In [8]:
np.random.randint(5, size = (2, 4))

array([[2, 4, 0, 2],
       [2, 2, 4, 1]])

In [9]:
np.random.randint(5, 25, size = (2, 4))

array([[11,  6, 22, 13],
       [11, 17, 10, 23]])

In [14]:
np.random.randint(1, [3, 50, 100])

array([ 2, 48, 60])

In [17]:
np.random.randint(1, [3, 50, 100], size = (5, 3))

array([[ 1, 41, 21],
       [ 1, 41, 76],
       [ 2,  8, 91],
       [ 1, 10, 17],
       [ 1, 36, 69]])

In [18]:
np.random.randint([1, 40, 90], [3, 50, 100], size = (5, 3))

array([[ 2, 44, 91],
       [ 2, 47, 92],
       [ 1, 48, 96],
       [ 1, 46, 90],
       [ 1, 47, 95]])

In [20]:
np.random.randint([2, 40, 90], [3, 50, 100], size = (5, 3))

array([[ 2, 44, 95],
       [ 2, 42, 99],
       [ 2, 44, 95],
       [ 2, 46, 95],
       [ 2, 43, 93]])

In [22]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr

array([18,  4, 18, 45, 12,  6, 46, 39, 10, 32])

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
ranarr.reshape(2,5)

array([[18,  4, 18, 45, 12],
       [ 6, 46, 39, 10, 32]])

In [27]:
ranarr

array([18,  4, 18, 45, 12,  6, 46, 39, 10, 32])

In [28]:
ranarr.max()

46

In [29]:
ranarr.argmax()  # maxin indexini verdi

6

In [31]:
ranarr.min()

4

In [32]:
ranarr.argmin()  # minin indexini verdi

1

In [34]:
arr.ndim

1

In [35]:
ranarr.ndim

1

In [36]:
barr = ranarr.reshape(2,5)

In [37]:
barr

array([[18,  4, 18, 45, 12],
       [ 6, 46, 39, 10, 32]])

In [38]:
barr.ndim  # number of array dimension

2

In [39]:
barr.shape  # tupple of array dimension

(2, 5)

In [40]:
arr.shape

(25,)

In [42]:
arr.dtype

dtype('int32')

In [43]:
a = np.random.randint(10, size = 10)

In [44]:
a

array([9, 4, 9, 3, 9, 2, 2, 5, 8, 7])

In [45]:
a.dtype

dtype('int32')

In [46]:
b = np.full((4,6), 2.2)

In [47]:
b

array([[2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2]])

In [48]:
b.dtype

dtype('float64')

In [49]:
c = np.full((4,6), "2.2")

In [50]:
c

array([['2.2', '2.2', '2.2', '2.2', '2.2', '2.2'],
       ['2.2', '2.2', '2.2', '2.2', '2.2', '2.2'],
       ['2.2', '2.2', '2.2', '2.2', '2.2', '2.2'],
       ['2.2', '2.2', '2.2', '2.2', '2.2', '2.2']], dtype='<U3')

In [51]:
c.dtype

dtype('<U3')

In [52]:
a.ndim  # bir boyutlu array/matris

1

In [53]:
b.ndim  # 2 boyutlu matris

2

In [54]:
a.size  # toplam eleman sayisi

10

In [55]:
b.size  # toplam eleman sayisi

24

#### Concatenation of the Arrays

In [56]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [57]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [58]:
z = np.array([7,8,9])

In [59]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2D Concatenate

In [60]:
a1 = np.concatenate([x,y]).reshape(2,3)

In [61]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
np.concatenate([a1, a1])  # axis sifir oldugu icin satir ekelme yaptik

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [63]:
np.concatenate([a1, a1], axis = 1) # axis bir oldugu icin sutun olarak ekledi

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### Splitting of the Arrays

In [67]:
x = np.random.randint(1, 100, size = 8)

In [68]:
x

array([41, 62, 83, 17, 78, 83, 50, 40])

In [70]:
np.split(x, [3,5])  # [:3][3:5][5:] bu sekilde 3 ayri arraye bölüyor

[array([41, 62, 83]), array([17, 78]), array([83, 50, 40])]

In [71]:
a, b, c = np.split(x, [3,5])

In [72]:
a

array([41, 62, 83])

In [73]:
b

array([17, 78])

In [74]:
c

array([83, 50, 40])

In [75]:
np.split(x, 4)  # equal division yapar

[array([41, 62]), array([83, 17]), array([78, 83]), array([50, 40])]

In [77]:
np.split(x, 2)

[array([41, 62, 83, 17]), array([78, 83, 50, 40])]

In [78]:
c[0]

83

In [79]:
m = np.arange(20).reshape(5,4)

In [80]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [81]:
np.split(m, [2, 4])  # satira göre bölüyor axis 0

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [82]:
np.split(m, [2, 4], axis = 1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]]),
 array([], shape=(5, 0), dtype=int32)]

In [84]:
np.vsplit(m, [2,4])  # satir satir bölüyor ayni split gibi

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [85]:
upper, lower = np.vsplit(m, [3])

In [86]:
upper

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
lower

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [88]:
np.vsplit(m, 5)  # 5 esit parcaya bölmeye calisir

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [89]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [90]:
np.hsplit(m, [2])  # sütün sütün bölüyor

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])]

In [91]:
left, right = np.hsplit(m, [2])

In [92]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

In [93]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [94]:
v = np.array([2,1,4,3,5])

In [95]:
v

array([2, 1, 4, 3, 5])

In [100]:
np.sort(v)  # orjinal matris ayni kalir

array([1, 2, 3, 4, 5])

In [101]:
v.sort()  # orjinal matrisi degistirir

In [102]:
v

array([1, 2, 3, 4, 5])

In [103]:
twoD = np.random.randint(5, 100, (3,3))

In [104]:
twoD

array([[58, 92, 97],
       [24, 16, 54],
       [11, 53, 74]])

In [113]:
np.sort(twoD, axis = 1)  # satirlar sabit sutunlari siraliyor, sütunlarin icinde islem yapiyoruz

array([[58, 92, 97],
       [16, 24, 54],
       [11, 53, 74]])

In [114]:
np.sort(twoD, axis = 0)  # sütunlar sabit satirlari siraliyor, satirlarin icinde islem yapiyoruz

array([[11, 16, 54],
       [24, 53, 74],
       [58, 92, 97]])

### Numpy Indexing and Selection

In [115]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
arr[8]

8

In [117]:
arr[-1]

10

In [118]:
arr[1:5]

array([1, 2, 3, 4])

In [119]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [121]:
# start:stop:step
arr[1::2]

array([1, 3, 5, 7, 9])

In [122]:
arr[0::2]

array([ 0,  2,  4,  6,  8, 10])

### Broadcasting

In [123]:
arr[0:5] = 100

In [124]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [125]:
a = [0,2,4,6,8]

In [126]:
a[0:3] = 100  # normal listelerde broadcasting olmuyor

TypeError: can only assign an iterable

In [127]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [136]:
slice_of_arr = arr[0:6]

In [137]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [138]:
slice_of_arr[:] = 99

In [139]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [140]:
arr  # orjinali bozuldu

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [141]:
arr_copy = arr.copy()

In [142]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [143]:
arr_copy[0:6] = [0,1,2,3,4,5]

In [144]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [145]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Indexing a 2D array (matrices)

In [147]:
arr_2d = np.array([[5,10,15],[20, 25, 30],[35,40,45]])  # liste icinde liste ile array ürettik

In [148]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [149]:
arr_2d[1]

array([20, 25, 30])

In [150]:
arr_2d[1][0]

20

In [151]:
arr_2d[1, 0]

20

In [155]:
arr_2d[:2, 1:]  # sag üst tarafi aldik

array([[10, 15],
       [25, 30]])

In [156]:
arr_2d[2, :]

array([35, 40, 45])

In [157]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [159]:
arr_2d[:,1]

array([10, 25, 40])

In [160]:
arr_2d[:,2]

array([15, 30, 45])

In [161]:
arr_2d[1,1] = 55

In [162]:
arr_2d

array([[ 5, 10, 15],
       [20, 55, 30],
       [35, 40, 45]])

In [163]:
arr_2d.dtype

dtype('int32')

In [164]:
arr_2d[0,0] = 3.3

In [165]:
arr_2d

array([[ 3, 10, 15],
       [20, 55, 30],
       [35, 40, 45]])

### Fancy Indexing

In [166]:
v = np.arange(0, 30, 3)

In [167]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [168]:
v[1]

3

In [169]:
v.size

10

In [170]:
idx = [1,3,5]  # istedigim index numaralarini bir liste icine koyuyorum.

In [172]:
v[idx]

array([ 3,  9, 15])

In [173]:
v[[1,3,5]]  # yukaridaki ile ayni sey

array([ 3,  9, 15])

In [176]:
arr2d = np.zeros((10,10), dtype = int)

In [177]:
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [178]:
arr2d.shape

(10, 10)

In [179]:
arr_length = arr2d.shape[1]

In [180]:
arr_length

10

In [181]:
arr2d[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [182]:
arr2d[3]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [183]:
for i in range(arr_length):
    arr2d[i] = i  # komple bir satiri temsil ediyor

In [184]:
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [185]:
arr2d[[2,4,6,8]]  # satirlari cagiriyorum 

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [186]:
arr2d[[2,6,4,9]]

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [187]:
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [188]:
# arr2d[[row indices],[column indices]]
jj = np.arange(1,17).reshape((4,4))
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [190]:
jj[[1, 2], [0, 3]]  # 2.satir 1.sütun = 5, 3.satir 4.sütun = 12

array([ 5, 12])

In [192]:
jj[[1, 2, 3], [0, 3, 3]]  # 11-->5, 23-->12, 33-->16

array([ 5, 12, 16])

In [195]:
jj[1, [1,3]]  # fancy ve normal bir arada

array([6, 8])

In [196]:
jj[[0,3], 1]  # fancy ve normal bir arada

array([ 2, 14])

### Using Basic Indexing and Fancy Indexing

In [197]:
jj[0:, [1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [198]:
jj[0:, [1,3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [199]:
jj[1:3, [1,2]]  # basic and fancy

array([[ 6,  7],
       [10, 11]])

In [200]:
jj[1:3, 1:3]  # basic and basic

array([[ 6,  7],
       [10, 11]])

### Selection

In [201]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [202]:
arr > 4  # Bool döndürür

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [203]:
arr > 90

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [206]:
bool_arr = arr > 90

In [207]:
arr[bool_arr]  # True olan degerleri döndürüyor

array([99, 99, 99, 99, 99, 99])

In [208]:
arr[arr > 90]  # ayni seyi bu da veriyor

array([99, 99, 99, 99, 99, 99])

In [210]:
arr[(arr != 99) & (arr != 9)]  # 99 ve 9 olmayanlar

array([ 6,  7,  8, 10])

In [211]:
arr[(arr%3==0) &(arr%2!=0)]  # 3 e bölünen tek sayilar

array([99, 99, 99, 99, 99, 99,  9])

### Aritmetic Operations

In [212]:
arr = np.arange(0,11)

In [213]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [214]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [215]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [216]:
arr / arr  # sifira bölümde isleme devam ediyor, 0 a bölüm icin nan uyarisi verdi

C:\Users\aliyi\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [217]:
1 / arr  # inf hatasi verdi ama isleme devam ediyor numpy in özelligi bu

C:\Users\aliyi\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [218]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [219]:
v-1

array([0, 1, 2, 3, 4])

In [220]:
v * 5

array([ 5, 10, 15, 20, 25])

In [222]:
v * 5 / 10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

### Universal Array Functions (math operations) numpyin orijinal sayfasindan

In [228]:
np.log10(10000)  # normalizasyon icin kullanilir, outlier lari baskilamak icin

4.0

In [229]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [230]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [231]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [232]:
np.sin(np.pi/2)

1.0