In [2]:
import numpy as np
import pandas as pd

In [3]:
pd.Series([10,83,3,4,5])

0    10
1    83
2     3
3     4
4     5
dtype: int64

In [4]:
ser = pd.Series([10,83,3,4,5])

In [5]:
ser

0    10
1    83
2     3
3     4
4     5
dtype: int64

***Basic Attributes***

In [6]:
type(ser)

pandas.core.series.Series

In [7]:
ser.dtype

dtype('int64')

In [8]:
ser.size

5

In [9]:
ser.ndim

1

In [12]:
ser.values  # lazy object

array([10, 83,  3,  4,  5], dtype=int64)

In [13]:
for i in ser.values:
    print(i)

10
83
3
4
5


In [14]:
[i for i in ser.values]

[10, 83, 3, 4, 5]

In [15]:
ser.head(3)  # icine yazdiginiz kadar satir gösterir

0    10
1    83
2     3
dtype: int64

In [16]:
ser.tail(3)  # sondan 3 satiri gösterir

2    3
3    4
4    5
dtype: int64

In [19]:
str = "clarusway"
pd.Series([i for i in str])  # burada bi liste olusturduk

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

**crating Pandas series by using a list, numpy array or dictionary**

In [21]:
labels =["a","b","c"]
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {"a":10, "b":20, "c":30}

In [22]:
pd.Series(data = my_list)

0    10
1    20
2    30
dtype: int64

In [23]:
pd.Series(data = my_list, index = labels)  # keyargument

a    10
b    20
c    30
dtype: int64

In [24]:
pd.Series(my_list, labels)  # argument

a    10
b    20
c    30
dtype: int64

In [25]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [26]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int32

In [27]:
pd.Series(d)  # dictionaray koyarsak keyler index olur valueler datanin kendisi olur

a    10
b    20
c    30
dtype: int64

In [28]:
mix_data = [1, "cat", True]

In [29]:
pd.Series(mix_data)

0       1
1     cat
2    True
dtype: object

In [30]:
str = "clarusway"
ser = pd.Series([i for i in str])

In [31]:
ser

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

In [32]:
ser.sort_values()

2    a
7    a
0    c
1    l
3    r
5    s
4    u
6    w
8    y
dtype: object

In [33]:
ser.sort_index()

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

In [36]:
ser.isin(["cow", "dog"])  # serinin icinde var mi yok mu onu gösteriyor var sa true veriyor 

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
dtype: bool

**Indexing Pandas Series**

In [48]:
ser1 = pd.Series([1,2,3,4], index = ["USA", "Germany", "USSR", "Japan"])

In [49]:
ser2 = pd.Series([1,2,5,4], index = ["USA", "Germany", "Italy", "Japan"])

In [50]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [51]:
ser1["USA"]  # indexi cagiriyorum value u aliyorum

1

In [52]:
ser2["Italy"]

5

In [53]:
labels

['a', 'b', 'c']

In [54]:
ser3 = pd.Series(data = labels)

In [55]:
ser3

0    a
1    b
2    c
dtype: object

In [56]:
ser3[0]

'a'

In [58]:
ser1 + ser2  # indexler ortak hareket ediyor

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [59]:
a = np.array([1,2,33,444,75])

In [60]:
a

array([  1,   2,  33, 444,  75])

In [62]:
panser = pd.Series(a)
panser

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [63]:
panser[0]  # pandas serisinden bir eleman döndurdu

1

In [64]:
panser[0:3]  # pandas serisini slicing yapiyoruz

0     1
1     2
2    33
dtype: int32

In [65]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [66]:
ser1["USA":"Japan"]  # indexin kendisini yazarsak hepsini getiriyor

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [71]:
ser1[2:3]  # sagda yazdigimizin bir eksigini alir

USSR    3
dtype: int64

In [70]:
ser1[2:4]

USSR     3
Japan    4
dtype: int64

In [72]:
panser = pd.Series([121,200,150,99], index = ["ali", "veli", "gül", "nur"])

In [73]:
panser

ali     121
veli    200
gül     150
nur      99
dtype: int64

In [74]:
panser["ali"]

121

In [75]:
panser[0]

121

In [76]:
panser[["veli", "nur"]]  # aradan cekip aldik, liste icinden aldik 

veli    200
nur      99
dtype: int64

In [77]:
panser[0:3]

ali     121
veli    200
gül     150
dtype: int64

In [78]:
panser["ali" : "nur"]

ali     121
veli    200
gül     150
nur      99
dtype: int64

**Several Selecting Attributes**

In [80]:
panser.index

Index(['ali', 'veli', 'gül', 'nur'], dtype='object')

In [81]:
panser.values

array([121, 200, 150,  99], dtype=int64)

In [82]:
panser.values.sort()

In [83]:
panser.values

array([ 99, 121, 150, 200], dtype=int64)

In [84]:
panser.items

<bound method Series.items of ali      99
veli    121
gül     150
nur     200
dtype: int64>

In [85]:
panser.items()

In [86]:
list(panser.items())

[('ali', 99), ('veli', 121), ('gül', 150), ('nur', 200)]

In [87]:
panser = pd.Series([121,200,150,99], index = ["ali", "veli", "gül", "nur"])

In [88]:
list(panser.items())

[('ali', 121), ('veli', 200), ('gül', 150), ('nur', 99)]

In [90]:
[(index, value) for index, value in panser.items()]

[('ali', 121), ('veli', 200), ('gül', 150), ('nur', 99)]

In [91]:
for index, value in panser.items():
    print(index, "-", value)

ali - 121
veli - 200
gül - 150
nur - 99


In [92]:
"mehmet" in panser

False

In [93]:
"ali" in panser

True

In [94]:
"gülnur" in panser

False

In [95]:
"gul" in panser

False

In [96]:
99 in panser

False

In [97]:
99 in panser.values

True

In [98]:
500 in panser.values

False

In [99]:
panser["veli"]

200

In [100]:
panser["veli"] = 571  # bir indexi cagirdik ve deger atadik, broadcasting

In [102]:
panser > 130  # tüm valueler bool olarak dönüyor

ali     False
veli     True
gül      True
nur     False
dtype: bool

In [104]:
panser[panser>130]  # conditioni köseli parantez ile yazarsak o conditiona uyan yeri bize sergiler.

veli    571
gül     150
dtype: int64

# DATA FRAMES

In [105]:
datam = [1,2,39,79,90]

In [106]:
datam

[1, 2, 39, 79, 90]

In [107]:
pd.DataFrame(datam, columns = ["column_name"])  # column_name baslik olarak geliyor

column_name
0            1
1            2
2           39
3           79
4           90

In [108]:
m = np.arange(1,10).reshape((3,3))

In [109]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
pd.DataFrame(m, columns = ["var1", "var2", "var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [111]:
pd.DataFrame(data = m, columns = ["var1", "var2", "var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [112]:
df = pd.DataFrame(m, columns = ["var1", "var2", "var3"])

In [113]:
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [114]:
df.head(1)

var1  var2  var3
0     1     2     3

In [115]:
df.head(2)

var1  var2  var3
0     1     2     3
1     4     5     6

In [116]:
df.tail(1)

var1  var2  var3
2     7     8     9

In [117]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [118]:
for i in df.columns:
    print(i)

var1
var2
var3


In [119]:
df.columns = ["new1", "new2", "new3"]

In [120]:
df

new1  new2  new3
0     1     2     3
1     4     5     6
2     7     8     9

In [121]:
type(df)

pandas.core.frame.DataFrame

In [122]:
df.shape

(3, 3)

In [124]:
df.ndim  # dimension, 2 boyutlu

2

In [125]:
df.size

9

In [127]:
df.values  # data ya ne girdiyse onu verir, numpy array verir

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
type(df.values)

numpy.ndarray

**Creating a Data Frame using a dict**

In [131]:
s1 = np.random.randint(10, size =5)
s2 = np.random.randint(10, size =5)
s3 = np.random.randint(10, size =5)

In [132]:
s1

array([3, 3, 8, 3, 0])

In [133]:
s2

array([5, 3, 0, 3, 3])

In [134]:
s3

array([1, 7, 2, 6, 9])

In [137]:
myDict = {"var1" : s1, "var2" : s2, "var3" : s3}  # keys= column name, data = values

In [138]:
df1 = pd.DataFrame(myDict)

In [139]:
df1

var1  var2  var3
0     3     5     1
1     3     3     7
2     8     0     2
3     3     3     6
4     0     3     9

**Read CSV (comma seperated) file**

In [141]:
pwd

'C:\\Users\\aliyi\\DATA SCIENCE'

In [146]:
pd.read_csv("ornekcsv.csv", delimiter = ";")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [149]:
df3 = pd.read_csv("ornekcsv.csv", delimiter = ";")  # githubdaki proje bununla yapilabilir, githubdan projeyi indir, tamamladiktan sonra kendi githubina yukle 

In [150]:
df3.head()

a    b    c
0  78   12  1.0
1  78   12  2.0
2  78  324  3.0
3   7    2  4.0
4  88   23  5.0

In [151]:
df1

var1  var2  var3
0     3     5     1
1     3     3     7
2     8     0     2
3     3     3     6
4     0     3     9

In [153]:
df1[1:3]  # satir,sütun indexi

var1  var2  var3
1     3     3     7
2     8     0     2

In [155]:
df1.index  # lazy object

RangeIndex(start=0, stop=5, step=1)

In [157]:
[i for i in df1.index]  # cok sik kullanilabilecek bir metod, daha sonra index numaralari baska bir yerde kullanilabilir

[0, 1, 2, 3, 4]

In [160]:
df1.index = ["a", "b", "c", "d", "e"]  # atama yaptik

In [161]:
df1

var1  var2  var3
a     3     5     1
b     3     3     7
c     8     0     2
d     3     3     6
e     0     3     9

In [163]:
df1["b" : "d"]  # slicelama da string olursa sinirlar dahil ediyor, rakam kullanirsak stop degerini dahil etmiyor

var1  var2  var3
b     3     3     7
c     8     0     2
d     3     3     6

In [164]:
# sütun isimleri arasinda var mi kontrol ediyorum

"var2" in df1

True

In [165]:
"joseph" in df1

False

**Indexing, selection and slicing methods and several attributes using different DatFrame**

In [166]:
from numpy.random import randn
np.random.seed(101)

In [167]:
df3 = pd.DataFrame(randn(5,4), index = "A B C D E".split(), columns = "W X Y Z".split())

In [168]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [169]:
df3 = pd.DataFrame(randn(5,4), "A B C D E".split(), "W X Y Z".split())

In [170]:
df3

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

**Selection and Indexing**

In [172]:
df3["W"]  # sütunu aldim, serieyi aldim daha dogrusu

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [174]:
type(df3["W"])  # Pandas Series

pandas.core.series.Series

In [175]:
df3["W"].values

array([ 0.30266545, -0.13484072,  0.80770591, -0.49710402, -0.11677332])

In [176]:
df3["W"].ndim

1

In [178]:
df3[["W"]]  # DataFrame döndü

W
A  0.302665
B -0.134841
C  0.807706
D -0.497104
E -0.116773

In [179]:
type(df3[["W"]]) 

pandas.core.frame.DataFrame

In [181]:
istedigimsütunlar = ["W", "Z"]

df3[istedigimsütunlar]  # bu bir DataFrame

W         Z
A  0.302665 -1.159119
B -0.134841  0.184502
C  0.807706  0.329646
D -0.497104  0.484752
E -0.116773  1.996652

In [182]:
WZ_df = df3[istedigimsütunlar]

In [183]:
WZ_df

W         Z
A  0.302665 -1.159119
B -0.134841  0.184502
C  0.807706  0.329646
D -0.497104  0.484752
E -0.116773  1.996652

In [184]:
df3[["W","Z"]]

W         Z
A  0.302665 -1.159119
B -0.134841  0.184502
C  0.807706  0.329646
D -0.497104  0.484752
E -0.116773  1.996652

In [187]:
# alttaki ikisi ayni sey
df3["W"]
df3.W  # bu kullanim builtinmethodlar ile karisacagindan cok tercih edilmiyor 

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [188]:
df3["W"]

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [189]:
df3["A" : "C"]

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646

In [190]:
df3["C" : "C"]

W        X         Y         Z
C  0.807706  0.07296  0.638787  0.329646